config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'


  resources :issues, only: [:index]
  
  namespace :users do
    resources :issues, only: [:index, :show]
    resources :bills, only: [:index, :show]
  end
  
  resources :users, only: [:new, :create, :show]

  post '/follow_issue', to: 'issue_follows#create', as: 'issue_follows'
  delete '/unfollow_issue', to: 'issue_follows#destroy', as: 'issue_unfollows'

  post '/follow_bill', to: 'bill_follows#create', as: 'bill_follows'
  delete '/unfollow_bill', to: 'bill_follows#destroy', as: 'bill_unfollows'

  get '/login', to: 'sessions#new', as: 'new_login'
  post '/login', to: 'sessions#create', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  has_many :user_bills
  has_many :users, through: :user_bills

  def self.from_pro_publica(raw_bill)
    bill = find_by(bill_id: raw_bill[:bill_slug]) || Bill.new
    bill.attributes = {
      bill_ref: raw_bill[:bill_id],
      bill_id: raw_bill[:bill_slug],
      title: raw_bill[:short_title],
      subject: raw_bill[:primary_subject],
      active: raw_bill[:active],
      enacted: raw_bill[:enacted]
    }
    bill.fix_nil_empty_title
    bill.fix_nil_empty_subject
    bill.save
    bill
  end

  def fix_nil_empty_title
    if title.nil? || title.empty?
      update(title: "Not Available. View full bill for information")
    end
  end

  def fix_nil_empty_subject
    if subject.nil? || subject.empty?
      update(subject: "Not Available. View full bill for information")
    end
  end

end

app/models/issue.rb
class Issue < ApplicationRecord
  has_many :user_issues
  has_many :users, through: :user_issues
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :user_issues
  has_many :issues, through: :user_issues
  has_many :user_bills
  has_many :bills, through: :user_bills
  validates :username, :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 5 }, on: :create

  def self.from_oauth(info)
    user = find_by(uid: info[:uid]) || User.new
    user.attributes = {
      uid: info[:uid],
      username: info[:info][:name],
      email: info[:info][:email],
      password: info[:uid],
      oauth_token: info[:credentials][:token],
      oauth_expire: info[:credentials][:expires_at],
      image: info[:info][:image]
    }
    user.save
    user
  end
end

app/models/user_bill.rb
class UserBill < ApplicationRecord
  belongs_to :user
  belongs_to :bill
end

app/models/user_issue.rb
class UserIssue < ApplicationRecord
  belongs_to :user
  belongs_to :issue
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user || User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def visitor?
    current_user.nil?
  end
  helper_method :visitor?

end

app/controllers/bill_follows_controller.rb
class BillFollowsController < ApplicationController

  def create
    user = current_user
    bill_ref = params[:bill_ref]
    bill = BillsSearch.find_and_generate(bill_ref)
    if user.bills.include?(bill)
      flash[:success] = "Already following Bill: #{bill.bill_id}"
      redirect_back(fallback_location: user_path(user))
    else
      user.bills << bill
      flash[:success] = %Q[Followed Bill: #{bill.bill_id}. <a href="/users/#{user.id}">See This Bill on Your Profile</a>]
      redirect_back(fallback_location: user_path(user))
    end
  end

  def destroy
    user = current_user
    @bill = Bill.find(params[:bill_id])
    user.bills.destroy(@bill)

    respond_to do |format|
      format.html { redirect_back(fallback_location: user_path(user)) }
      format.js
    end
  end

end

app/controllers/issue_follows_controller.rb
class IssueFollowsController < ApplicationController

  def create
    user = current_user
    issue = Issue.find(params[:issue_id])
    if user.issues.include?(issue)
      flash[:success] = "Already following Issue: #{issue.name}"
      redirect_back(fallback_location: user_path(user))
    else
      user.issues << issue
      flash[:success] = %Q[Followed Issue: #{issue.name}. <a href="/users/#{user.id}">See This Issue on Your Profile</a>]
      redirect_back(fallback_location: user_path(user))
    end
  end

  def destroy
    user = current_user
    @issue = Issue.find(params[:issue_id])
    user.issues.destroy(@issue)
    # flash[:success] = "Unfollowed Issue: #{@issue.name}"

    respond_to do |format|
      format.html { redirect_back(fallback_location: user_path(user)) }
      format.js
    end
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  def index
    @issues = Issue.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new 
  end

  def create
    default_login? ? user = default_login_info : user = oauth_login_info
    if user
      session[:user_id] = user.id
      flash[:success] = "Successfully Signed in as #{user.username}"
      redirect_to user_path(user)
    else
      flash[:failure] = "Failed to Sign In"
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    flash[:success] = "Successfully Signed Out"
    redirect_to root_path
  end

  private

    def authenticated?(user)
      user && user.authenticate(params[:session][:password])
    end

    def default_login?
      params[:session]
    end

    def default_login_info
      user = User.find_by(username: params[:session][:username])
      if user && authenticated?(user)
        user
      end
    end

    def oauth_login_info
      User.from_oauth(request.env['omniauth.auth'])
    end

end

app/controllers/users/bills_controller.rb
class Users::BillsController < ApplicationController

  def index
    user = current_user
    @bills = user.bills

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    bill_ref = params[:bill_ref]
    @bill = BillsSearch.get_full(bill_ref)
  end

end

app/controllers/users/issues_controller.rb
class Users::IssuesController < ApplicationController

  def index
    user = current_user
    @issues = user.issues

    respond_to do |format|
      format.html
      format.js
    end

  end

  def show
    @user = current_user
    @issue = Issue.find(params[:id])
    @bills_by_issue = BillsSearch.by_issue(@issue.slug)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new    
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = current_user

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_has_issue_bill?(user, issue_bill)
    issue_bill_id = issue_bill.bill_number
    if user.bills.find_by(bill_id: issue_bill_id).nil?
      return false
    else
      return true
    end
  end

  

end

app/views/bill_follows/destroy.js.erb
var element = document.getElementById("<%=j "bill-#{@bill.id}" %>");
element.remove();

app/views/issue_follows/destroy.js.erb
var element = document.getElementById("<%=j "issues-row-#{@issue.id}" %>");
element.remove();

app/views/issues/index.html.erb
<div class="column is-10 is-offset-1 is-multiline">
  <div class="level">
    <h1 class="level-item has-text-centered is-size-1">All Available Issues</h1>
  </div>
  <div class="columns is-multiline">
    <% @issues.each do |issue| %>
    <div class="column is-4">
      <div class>
        <div class="card issue<%= issue.id %>">
          <header class="card-header">
            <p class="card-header-title">
            <%= issue.name %>
            </p>
            <% if current_user.issues.include?(issue) %>
            <p class="card-header-icon">
              <span class="tag is-success">Following</span>
            </p>
            <% end %>
          </header>
          <footer class="card-footer">
            <% if current_user.issues.include?(issue) %>
            <%= link_to 'Unfollow', issue_unfollows_path(issue_id: issue.id), class: 'card-footer-item', method: :delete %>
            <% else %>
            <%= link_to 'Follow', issue_follows_path(issue_id: issue.id), class: 'card-footer-item', method: :post %>
            <% end %>
          </footer>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="level">
    <%= link_to "View Your Profile", user_path(current_user), class: 'level-item button is-danger is-outlined' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CitizenSentinel</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<nav class="navbar is-light" role="navigation" aria-label="main navigation">
	  <div class="navbar-brand">
	    <a class="navbar-item" href="/">
	      <img src="https://d30y9cdsu7xlg0.cloudfront.net/png/41077-200.png" alt="congress", width="20">
	    	CitizenSentinel
	    </a>

	    <button class="button navbar-burger">
	      <span></span>
	      <span></span>
	      <span></span>
	    </button>
	  </div>

	  <div class="navbar-menu">

		  <div class="navbar-end">
		  	<% if visitor? %>
		  	<div class="navbar-item signup-nav">
		  		<%= link_to "Sign Up", new_user_path, class: "button is-link" %>
		  	</div>
		  	<div class="navbar-item signin-nav">
		  		<%= link_to "Sign In", new_login_path, class: "button is-danger" %>
		  	</div>
		  	<% elsif current_user %>
		  	<div class="navbar-item">
		  		<%= link_to user_path(current_user), class: 'button is-danger is-outlined' do %>
				 	<span class="icon is-small">
      					<i class="fa fa-user"></i>
    				</span>
    				<span>
    					My Profile
    				</span>
				<% end %>
		  	</div>
		  	<div class="navbar-item">
		  		<%= link_to "Sign Out", logout_path, class: "button is-link", method: :delete %>
		  	</div>
		  	<% end %>
		  </div>
	  	
	  </div>


	</nav>

	<% flash.each do |type, message| %>
		<% if flash[:success] %>
	    <div class="flash-success">
	      <%= sanitize(message) %>
	    </div>
	    <% elsif flash[:failure] %>
	    <div class="flash-failure">
	      <%= sanitize(message) %>
	    </div>
	    <% end %>
    <% end %>

    <%= yield %>

	<footer class="footer footer-pad">
	  <div class="container">
	    <div class="content has-text-centered">
	      <p>
	        <strong>CitizenSentinel</strong> by Aaron Hursh</a>.
	      </p>
	      <p>
	      	2017
	      </p>
	    </div>
	  </div>
	</footer>
  </body>
</html>

app/views/users/_profile.html.erb
<div class="level">
  <h1 class="level-item has-text-centered is-size-1"><%= current_user.username %></h1>
</div>
<div class="level">
  <h1 class="level-item has-text-centered is-size-3"><%= current_user.email %></h1>
</div>
<div class="level">
  <h1 class="level-item has-text-centered is-size-3"><%= link_to "Follow Issues", issues_path, class: "button is-link" %></h1>
</div>

app/views/users/bills/_bills.html.erb
<div class="bills">
  <div class="level">
    <h1 class="level-item has-text-centered is-size-2">Bills You Follow</h1>
  </div>
  <% if @bills.empty? %>
  <div class="level">
      <h3 class="level-item has-text-centered">
        You do not currently follow any bills. Add and view an issue to select bills to follow.
      </h3>
  </div>
  <% else %>
  <table class="table is-fullwidth is-striped">
    <thead>
      <tr>
        <th>Bill ID</th>
        <th>Title</th>
        <th>Subject</th>
        <th>Active?</th>
        <th>Enacted?</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <% @bills.each do |bill| %>
    <tbody>
      <tr id="bill-<%= bill.id %>">
        <td><%= bill.bill_id %></td>
        <td><%= bill.title %></td>
        <td><%= bill.subject %></td>
        <td><%= bill.active.to_s %></td>
        <td><%= bill.enacted.to_s %></td>
        <td><%= link_to "View Bill", users_bill_path(bill, bill_ref: bill.bill_ref), class: 'button is-link is-outlined is-small' %></td>
        <td><%= link_to "Unfollow", bill_unfollows_path(bill_id: bill.id), method: :delete, remote: true, name: 'bill-unfollow-button', class: 'button is-danger is-outlined is-small' %></td>
      </tr>
    </tbody>
    <% end %>
  </table> 
  <% end %>
  <div class="level">
    <h1 class="level-item has-text-centered is-size-3"><%= link_to "Follow Issues", issues_path, class: "button is-link" %></h1>
  </div>
</div>

app/views/users/bills/index.html.erb
<div class="bills">
  <h1>Bills You Follow</h1>
  <% @bills.each do |bill| %>
  <table>
    <thead>
      <tr>
        <th>Bill ID</th>
        <th>Title</th>
        <th>Subject</th>
        <th>Active?</th>
        <th>Enacted?</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <tr id="bill-<%= bill.id %>">
        <td><%= bill.bill_id %></td>
        <td><%= bill.title %></td>
        <td><%= bill.subject %></td>
        <td><%= bill.active.to_s %></td>
        <td><%= bill.enacted.to_s %></td>
        <td><%= link_to "View Bill", users_bill_path(bill, bill_ref: bill.bill_ref) %></td>
        <td><%= link_to "Unfollow", bill_unfollows_path(bill_id: bill.id), method: :delete %></td>
      </tr>
    </tbody>
  </table> 
  <% end %>
</div>

app/views/users/bills/index.js.erb
$("#content").html("<%= j (render "bills") %>");

app/views/users/bills/show.html.erb
<div class="column is-10 is-offset-1">

  <div class="level">
    <h1 class="bill-number level-item has-text-centered is-size-1"><%= @bill.number %></h1>
  </div>

  <div class="level">
    <h4 class="introduced-date level-item has-text-centered"><%= @bill.intro_date %></h4>
  </div>

  <div class="level">
    <h2 class="short-title level-item has-text-centered is-size-2"><%= @bill.short_title %></h2>
  </div>

  <div class="column is-4 is-offset-4">
    <div class="level">
      <%= link_to "See this bill on Congress.gov", @bill.congressdotgov, class: 'congressdotgov button is-link is-outlined level-item' %>
    </div>
    <div class="level">
      <%= link_to "See this bill at Govtrack", @bill.govtrack, class: 'govtrack button is-link is-outlined level-item' %>
    </div>
  </div>

  <div class="content">
    <br>
    <h3 class="sponsor has-text-centered">Sponsor: <%= @bill.sponsor %></h3>
    <h3 class="committees has-text-centered"><%= @bill.committees %></h3>
    <h3 class="subject has-text-centered"><%= @bill.subject %></h3>
    <br>
    <p class="summary has-text-centered"><%= @bill.summary %></p>
    <br>
    <h2 class="has-text-centered">Actions</h2>
    <br>
  </div>

  <% @bill.actions.each do |action| %>
  <article class="media actions">
    <figure class="media-left">
      <p class="number">
        <%= action[:id] %>
      </p>
    </figure>
    <div class="media-content">
      <div class="content has-text-centered">
        <h3>
          <%= action[:description] %>
        </h3>
      </div>
      <nav class="level is-mobile">
        <div class="level-item">
          <p class="has-text-centered">
            <%= action[:action_type] %> - <%= action[:chamber] %>
          </p>
        </div>
      </nav>
    </div>
    <div class="media-right">
      <p>
        <%= action[:datetime] %>
      </p>
    </div>
  </article>
  <% end %>

</div>

app/views/users/issues/_issues.html.erb
<div class="issues column is-4 is-offset-4">
  <div class="level">
    <h1 class="level-item has-text-centered is-size-2">Issues You Follow</h1>
  </div>
  <% if @issues.empty? %>
  <div class="level">
      <h3 class="level-item has-text-centered">
        You do not currently follow any Issues.
      </h3>
  </div>
  <% else %>
  <table class="table is-fullwidth is-striped">
    <thead>
      <tr>
        <th>Issue</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <% @issues.each do |issue| %>
    <tbody>
      <tr id="issues-row-<%= issue.id %>">
        <td><%= issue.name %></td>
        <td><%= link_to "Check Activity", users_issue_path(issue), class: 'button is-link is-outlined is-small' %></td>
        <td><%= link_to 'Unfollow', issue_unfollows_path(issue_id: issue.id), class: 'button is-danger is-outlined is-small', remote: true, method: :delete %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <% end %>
  <div class="level">
    <h1 class="level-item has-text-centered is-size-3"><%= link_to "Follow Issues", issues_path, class: "button is-link" %></h1>
  </div>
</div>

app/views/users/issues/index.html.erb
<div class="issues">
  <h1>Issues You Follow</h1>
  <% @issues.each do |issue| %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= issue.name %></td>
        <td><%= link_to "Check Activity", users_issue_path(issue), class: 'button is-link is-outlined is-small' %></td>
      </tr>
    </tbody>
  </table> 
  <% end %>
</div>

app/views/users/issues/index.js.erb
$("#content").html("<%= j (render "issues") %>");

app/views/users/issues/show.html.erb
<div class="column is-10 is-offset-1">
  <div class="level">
    <h1 class="level-item has-text-centered is-size-1">
      Recent Activity for Issue: <%= @issue.name %>
    </h1>
  </div>


  <% @bills_by_issue.each do |issue_bill| %>
  <article class="media bill">
    <div class="media-content">
      <div class="content">
        <p class="title">
          <strong class="bill_number"><%= issue_bill.bill_id %></strong> <small class="committees"> - <%= issue_bill.committees %></small> 
        </p>
        <p>
          <small><%= issue_bill.title %></small>
        </p>
        <p class="last_major_action">
          <small class="last_action_date"><%= issue_bill.last_action_date %></small>
          <small> - <%= issue_bill.last_major_action %></small>
        </p>
      </div>
      <nav class="level is-mobile">
        
      </nav>
    </div>
    <div class="media-right">
      <% if user_has_issue_bill?(@user, issue_bill) %>
        <div class="media-right followed-bill">
          <a class="button is-link" title="Disabled button" disabled>Following</a>
        </div>
      <% else %>
        <div class="level-left">
          <%= link_to "Follow this Bill", bill_follows_path(bill_ref: issue_bill.bill_ref), method: :post, class: 'button is-link is-outlined'  %>
        </div>
      <% end %>
    </div>
  </article>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="column is-4 is-offset-4">

  <div class="level">
    <h1 class="level-item has-text-centered is-size-1">Create an Account</h1>
  </div>
  <%= form_for @user do |f| -%>
  <div class="field">
      <%= f.label :username, "Username", class: 'label' %>
      <div class="control has-icons-left">
        <%= f.text_field :username, class: 'input' %>
        <span class="icon is-small is-left">
          <i class="fa fa-user"></i>
        </span>
      </div>
      <p class="help">Enter a Username that is unique to you</p>
  </div>
  <div class="field">
      <%= f.label :email, "Email", class: 'label' %>
      <div class="control has-icons-left">
        <%= f.text_field :email, class: 'input' %>
        <span class="icon is-small is-left">
          <i class="fa fa-envelope"></i>
        </span>
      </div>
      <p class="help">Just incase you forget anything</p>
  </div>
  <div class="field">
      <%= f.label :password, "Password", class: 'label' %>
      <div class="control has-icons-left">
        <%= f.password_field :password, class: 'input' %>
        <span class="icon is-small is-left">
          <i class="fa fa-lock"></i>
        </span>
      </div>
      <p class="help">Make it a good one so you don't get Equifaxed</p>
  </div>
  <div class="field ">
      <%= f.label :password_confirmation, "Password Confirmation", class: 'label' %>
      <div class="control has-icons-left">
        <%= f.password_field :password_confirmation, class: 'input' %>
        <span class="icon is-small is-left">
          <i class="fa fa-lock"></i>
        </span>
      </div>
      <p class="help">Let me hear you say it one more time</p>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit "Create Account", class: 'button is-link', method: :post %>
    </div>
  </div>
  <% end %>
  <div class="level">
    <h1 class="level-item has-text-centered is-size-1">or</h1>
  </div>
  <div class="level">
    <p class="level-item has-text-centered">
      <a href="/auth/facebook" class="button is-link is-large", id="facebook-login">
        <span class="icon is-medium">
          <i class="fa fa-facebook"></i>
        </span>
        <span>Sign Up With Facebook</span>
      </a>
    </p>
  </div>

</div>

app/views/users/show.html.erb
<div class="tabs is-centered">
  <ul>
    <li><%= link_to "Profile", user_path(@user), remote: true %></li>
    <li><%= link_to "Followed Issues", users_issues_path, remote: true %></li>
    <li><%= link_to "Followed Bills", users_bills_path, remote: true %></li>
  </ul>
</div>





<div id="content">
  <div class="level">
    <h1 class="level-item has-text-centered is-size-1"><%= current_user.username %></h1>
  </div>
  <div class="level">
    <h1 class="level-item has-text-centered is-size-3"><%= current_user.email %></h1>
  </div>
  <div class="level">
    <h1 class="level-item has-text-centered is-size-3"><%= link_to "Follow Issues", issues_path, class: "button is-link" %></h1>
  </div>
</div>

app/views/users/show.js.erb
$("#content").html("<%= j (render "profile") %>");

app/views/welcome/index.html.erb
<div class="column is-4 is-offset-4">

	<div class="image is-square">
		<img src="https://d30y9cdsu7xlg0.cloudfront.net/png/41077-200.png" alt="congress">
	</div>

	<div class="level">
		<h1 class="level-item has-text-centered is-size-1">CitizenSentinel</h1>
	</div>

</div>


<div class="column is-4 is-offset-4">
	<% if visitor? %>
	<div class="card">
		<div class="card-header">
			<div class="card-header-title is-centered">
				Sign Up To Track Legislative Action
			</div>
		</div>
		<div class="card-content">
			<p class="is-centered">
				Do you know what members of congress are up to? Sign up to track issues and bills. Become an engaged citizen today.
			</p>
		</div>
		<div class="card-footer">
			<%= link_to "Sign Up", new_user_path, class: "card-footer-item" %>
			<%= link_to "Sign In", new_login_path, class: "card-footer-item" %>
		</div>
	</div>
	<% else %>
	<div class="card">
		<div class="card-header">
			<div class="card-header-title is-centered">
				About Citizen Sentinel
			</div>
		</div>
		<div class="card-content">
			<p class="is-centered">
				We all know the political issues that are important to us, but most of us are not able to track the actual legislation that affects those issues. News media is necessarily scope limited, so we don't see every legislative action that affects us. Raw data is nearly impossible for the layman to parse and relate to the issues we prioritize. Americans are thus disconnected from one of the most important features of civic society: law-making.
			</p>
		</div>
			<div class="card-footer">
		  <%= link_to user_path(current_user), class: 'card-footer-item' do %>
				<span class="icon is-small">
      		<i class="fa fa-user"></i>
    		</span>
    		<span>
    			View Your Profile
    		</span>
			<% end %>
		 </div>
	</div>
	<% end %>
</div>
	